format_version: 3
pipelines:
  build_publish_image:
    group: codeigniter-example
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: https://github.com/zufardhiyaulhaq/codeIgniter-example.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - build_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: docker-builder-agent
            artifacts:
            - external:
                id: codeigniter-example
                store_id: docker-private-registry
                configuration:
                  options:
                    Image: ${DOCKER_REGISTRY_URL}/codeigniter-example
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKER_REGISTRY_URL/codeigniter-example:$GO_PIPELINE_LABEL . -f Dockerfile
                command: /bin/bash
                run_if: passed