format_version: 3
pipelines:
  deploy_to_development:
    group: codeigniter-example
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 2
    environment_variables:
    materials:
      upstream:
        pipeline: build_publish_image
        stage: build_publish_image
        name: upstream
    stages:
    - deploy_to_development:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: development-agent
            tasks:
            - exec:
                arguments:
                command: ./app-deployment.sh
                run_if: passed
