format_version: 3
pipelines:
  deploy_to_staging:
    group: codeigniter-example
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 3
    environment_variables:
    materials:
      upstream:
        pipeline: deploy_to_development
        stage: deploy_to_development
        name: upstream
      SourceCodeRepo:
        git: https://github.com/zufardhiyaulhaq/codeIgniter-example.git
        shallow_clone: false
        auto_update: true
        branch: master
        name: SourceCodeRepo
    stages:
    - deploy_to_staging:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: staging-agent
            tasks:
            - exec:
                arguments:
                - app-deployment.sh
                command: /bin/bash
                run_if: passed
