format_version: 3
pipelines:
  deploy_to_staging:
    group: codeigniter-example
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 3
    environment_variables:
    materials:
      upstream:
        pipeline: deploy_to_development
        stage: deploy_to_development
        name: upstream
    stages:
    - deploy_to_staging:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: staging-agent
            tasks:
            - fetch:
                artifact_id: codeigniter-example
                pipeline: build_publish_image
                stage: build_publish_image
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                command: ./app-deployment.sh
                run_if: passed

